;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        vundo
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        dired
        find-file
        org-self-insert-command
        wdired--self-insert
        ))
